defaults: &defaults
  host: localhost
  raise_not_found_error: false

test:
  <<: *defaults
  database: artaround_test

development:
  clients:
    default:
      database: artaround
      hosts:
        - localhost:27017
      autocreate_indexes: true



# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>

